{
 "title": "Home",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "days",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 8640000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*32800/100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "memory_usage" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 16  * 43200/100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "cpu_usage" }
     ]
    }
   ]
  },
  {
   "title": "Plex Transcodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "plex_info",
     "query": "SELECT \"transcodes\" FROM \"plex_info\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "transcodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Serier",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "storage_data",
     "query": "SELECT last(\"value\")  * 8192 FROM \"storage_data\" WHERE \"sensor\" = 'volcapacity' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "serier" }
     ]
    }
   ]
  },
  {
   "title": "Filmer",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "measurement": "storage_data",
     "query": "SELECT last(\"value\")  * 8192 FROM \"storage_data\" WHERE \"sensor\" = 'volcapacity' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "hd" }
     ]
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "storage_data",
     "query": "SELECT last(\"value\")  * 8192 FROM \"storage_data\" WHERE \"sensor\" = 'volcapacity' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "downloads" }
     ]
    }
   ]
  },
  {
   "title": "Random",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "storage_data",
     "query": "SELECT last(\"value\")  * 8192 FROM \"storage_data\" WHERE \"sensor\" = 'volcapacity' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "random" }
     ]
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage_data",
     "query": "SELECT last(\"value\")  * 8192 FROM \"storage_data\" WHERE \"sensor\" = 'volused' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "total" }
     ]
    }
   ]
  },
  {
   "title": "Total Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage_data",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "diskname", "operator": "=", "value": "raidspace" }
     ]
    }
   ]
  },
  {
   "title": "ESXi CPU and Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "6",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "7",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "8",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "10",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "11",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "11" }
     ]
    },
    {
     "alias": "12",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "13",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "14",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "14" }
     ]
    },
    {
     "alias": "15",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "15" }
     ]
    },
    {
     "alias": "16",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu_number", "operator": "=", "value": "16" }
     ]
    },
    {
     "alias": "Mem",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esxi_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "memory_usage" }
     ]
    }
   ]
  },
  {
   "title": "Internet Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "WAN Rx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth1wan" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" }
     ]
    },
    {
     "alias": "WAN Tx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth1wan" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "outbound" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "LAN Rx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2lan" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "inbound" }
     ]
    },
    {
     "alias": "LAN Tx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2lan" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "outbound" }
     ]
    }
   ]
  },
  {
   "title": "CPU FANSPEED",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fanA" }
     ]
    }
   ]
  },
  {
   "title": "RAID5 Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "RAID" },
      { "condition": "AND", "key": "card", "operator": "=", "value": "RAID5" }
     ]
    }
   ]
  },
  {
   "title": "RAID1 Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "RAID" },
      { "condition": "AND", "key": "card", "operator": "=", "value": "RAID1" }
     ]
    }
   ]
  },
  {
   "title": "RAIDCARD TEMP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "raidtemp" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 11 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "cputemp" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "SERIER",
     "groupBy": [
      { "params": [ "diskname" ], "type": "tag" }
     ],
     "measurement": "storage_data",
     "query": "SELECT last(\"diskspace\") * 1024 FROM \"storage_data\" WHERE (\"host\" = 'storage' AND \"diskname\" = 'serier') AND $timeFilter GROUP BY \"diskname\"",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "serier" }
     ]
    },
    {
     "alias": "FILMER",
     "groupBy": [
      { "params": [ "diskname" ], "type": "tag" }
     ],
     "measurement": "storage_data",
     "query": "SELECT last(\"diskspace\") * 1024 FROM \"storage_data\" WHERE (\"host\" = 'storage' AND \"diskname\" = 'hd') AND $timeFilter GROUP BY \"diskname\"",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "hd" }
     ]
    },
    {
     "alias": "DOWNLOADS",
     "groupBy": [
      { "params": [ "diskname" ], "type": "tag" }
     ],
     "measurement": "storage_data",
     "query": "SELECT last(\"diskspace\") * 1024 FROM \"storage_data\" WHERE (\"host\" = 'storage' AND \"diskname\" = 'downloads') AND $timeFilter GROUP BY \"diskname\"",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "downloads" }
     ]
    },
    {
     "alias": "RANDOM",
     "groupBy": [
      { "params": [ "diskname" ], "type": "tag" }
     ],
     "measurement": "storage_data",
     "query": "SELECT last(\"diskspace\") * 1024 FROM \"storage_data\" WHERE (\"host\" = 'storage' AND \"diskname\" = 'random') AND $timeFilter GROUP BY \"diskname\"",
     "select": [
      [
       { "params": [ "diskspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "storage" },
      { "condition": "AND", "key": "diskname", "operator": "=", "value": "random" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "TOP FAN",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan1" }
     ]
    },
    {
     "alias": "FRONT FAN 1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan2" }
     ]
    },
    {
     "alias": "FRONT FAN 2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan3" }
     ]
    },
    {
     "alias": "BOTTOM FAN",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan4" }
     ]
    },
    {
     "alias": "BACK FAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan5" }
     ]
    },
    {
     "alias": "RAID FAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fan6" }
     ]
    },
    {
     "alias": "CPU1 FAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fanA" }
     ]
    }
   ]
  },
  {
   "title": "LSI RAID-5 | 8x3TB",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 13 },
   "targets": [
    {
     "alias": "$tag_diskname",
     "groupBy": [
      { "params": [ "diskname" ], "type": "tag" }
     ],
     "measurement": "storage_data",
     "select": [
      [
       { "params": [ "disktemperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "LSI-RAID5" }
     ]
    }
   ]
  },
  {
   "title": "Host Temps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "cputemp" }
     ]
    },
    {
     "alias": "System Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "systemtemp" }
     ]
    },
    {
     "alias": "Peripheral Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "periphtemp" }
     ]
    },
    {
     "alias": "PCH Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "query": "SELECT last(\"value\") FROM \"health_data\" WHERE (\"sensor\" = 'pchtemp') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "pchtemp" }
     ]
    },
    {
     "alias": "RAID Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "raidtemp" }
     ]
    }
   ]
  }
 ]
}